# Generated by Django 2.2.12 on 2021-03-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_pokemon', models.ImageField(upload_to='image', blank=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
